config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  resources :users, only: %i[new create show edit update]
  resources :sessions, only: %i[new create destroy]

  namespace :admin do
    resources :users
    resources :tasks, only: [:index]
  end

  resources :labels
end

app/models/label.rb
# frozen_string_literal: true

class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :tasks, through: :labelings
  belongs_to :user, optional: true

  validates :name, presence: true, length: { in: 1..50 }, uniqueness: { scope: :user,
    message: "同じ名前のラベルを保存することはできません" }

end

app/controllers/labels_controller.rb
# frozen_string_literal: true

class LabelsController < ApplicationController
  before_action :logged_in?
  before_action :set_label, only: %i[show edit update destroy]

  def index
    @labels = current_user.labels
  end

  def show; end

  def new
    @label = Label.new
  end

  def edit; end

  def create
    @label = Label.new(label_params)
    if @label.save
      redirect_to @label, notice: 'ラベルの登録が完了しました'
    else
      flash[:danger] = '保存に失敗しました'
      render :new
    end
  end

  def update
    destroy_all_tasks if params[:label][:task_ids].blank?
    if @label.update(label_params)
      redirect_to @label, notice: 'ラベルの更新が完了しました'
    else
      flash[:danger] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @label.destroy!
    redirect_to labels_url, notice: 'ラベルを削除しました'
  end

  private

  def set_label
    @label = current_user.labels.find(params[:id])
  end

  def label_params
    params.require(:label).permit(:name, :user_id, task_ids: [])
  end

  def destroy_all_tasks
    @label.tasks.destroy_all
  end
end

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true) do |form| %>

  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "エラー") %> タスクの保存に失敗しました:</h2>
      <ul>
        <% label.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-6">
      <p><label>ラベル名</label></p>
      <input type="text" class="form-control input-form" name="label[name]" value="<%=@label.name%>">
    </div>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="row">
    <div class="form-group col-md-6">
    <p><label>タスク名</label></p>
      <% current_user.tasks.each do |task| %>
        <%= form.check_box :task_ids, { multiple: true, checked: @label.tasks.find_by(id: task.id).present?, include_hidden: false }, task[:id] %>
        <label class='badge badge-secondary'><%= task.name %></label>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-6">
      <button type="submit" class="btn btn-primary" name="commit">登録</button>
    </div>
  </div>

<% end %>

app/views/labels/_label.html.erb
<tr>
  <td class="label_row"><%= label.name %></td>

  <td>
  <% label.tasks.each do |task| %>
    <span class="label label-default"><%= task.name %></span>
  <% end %>
  </td>

  <td><%= label.created_at.strftime("%Y年%m月%d日 %H時%M分") %></td>
  <td><%= link_to '詳細', label %></td>
  <td><%= link_to '編集', edit_label_path(label) %></td>
  <td><%= link_to '削除', label, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } %></td>

</tr>

app/views/labels/edit.html.erb
<h4>タスク編集</h4>

<%= render 'form', label: @label %>

<div class="row">
  <div class="form-group col-md-6">
    <%= link_to '詳細', @label %> <%= link_to '戻る', labels_path %>
  </div>
</div>

app/views/labels/index.html.erb
<div class="container-fluid">

  <div class="row">
    <h4> ラベル一覧 </h4>
  </div>

  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>ラベル名</th>
        <th>ラベルタスク</th>
        <th>作成日</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <%= render @labels %>
    </tbody>
  </table>
  <%= link_to 'ラベルの登録', new_label_path %>

</div>

app/views/labels/new.html.erb
<h4>ラベルの登録</h4>

<%= render 'form', label: @label %>

<div class="row">
  <div class="form-group col-md-6">
    <p><%= link_to '戻る', labels_path %></p>
  </div>
</div>

app/views/labels/show.html.erb
<h4>ラベル詳細</h4>

<div class="row">
  <div class="form-group col-md-6">
    <label>ラベル名</label>
      <input type="text" readonly class="form-control show-form" value="<%=@label.name%>">
  </div>
</div>

<div class="row">
  <div class="form-group col-md-6">
    <label>タスク</label>
    <div>
      <% @label.tasks.each do |task| %>
        <label class='badge badge-secondary'><%= task.name %></label>
      <% end %>
    </div>
  </div>
</div>


<div class="row">
  <div class="form-group col-md-6">
    <%= link_to '編集', edit_label_path(@label) %>
    <%= link_to '戻る', labels_path %>
  </div>
</div>