config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  resources :users, only: %i[new create show edit update]
  resources :sessions, only: %i[new create destroy]

  namespace :admin do
    resources :users
    resources :tasks, only: [:index]
  end

  resources :labels
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_destroy :stop_admin_destroy
  before_update :stop_admin_update

  has_many :tasks, dependent: :destroy
  has_many :labels, dependent: :destroy

  # secure password
  has_secure_password

  # validation
  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }

  # scope
  scope :name_like,  ->(query) { where('name LIKE ?', "%#{query}%") }
  scope :name_order, -> { order(name: :asc) }

  # call back
  private

  def stop_admin_destroy
    if User.where(admin: true).count == 1
      throw(:abort) if admin.present?
    end
  end

  def stop_admin_update
    if User.where(admin: true).count == 1
      if User.where(admin: true).ids.include?(self.id)
        throw(:abort)
      end
    end
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  before_action :logged_in?
  before_action :admin_check
  before_action :user_find, only: %i[show edit update destroy]

  def index
    @users = if params[:name].present?
               User.page(params[:page]).name_like(params[:name])
             elsif params[:name_order]
               User.page(params[:page]).name_order
             else
               User.all.page(params[:page])
             end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user), notice: '会員登録が完了しました。'
    else
      render 'new'
    end
  end

  def show
    @tasks = @user.tasks.recent
  end

  def edit; end

  # アップデートアクション
  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: '会員情報を変更しました。'
    else
      flash[:danger] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: 'ユーザを削除しました'
    else
      flash[:danger] = '削除に失敗しました'
      redirect_to admin_users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def user_find
    @user = User.find(params[:id])
  end

  def admin_check
    if current_user.admin != true
      flash[:danger] = '権限がありません'
      redirect_to tasks_path
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :user_check, only: %i[show edit update]
  before_action :user_find, only: %i[show edit update]

  def new
    if current_user.blank?
      @user = User.new
    else
      flash[:danger] = '既に登録済みです'
      redirect_to tasks_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: '会員登録が完了しました。'
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  # アップデートアクション
  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: '会員情報を変更しました。'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def user_find
    @user = current_user
  end

  def user_check
    if session[:user_id] != params[:id].to_i
      flash[:danger] = '別のユーザ情報は確認できません'
      redirect_to tasks_path
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      admin_users_path
    elsif action_name == 'edit'
      admin_user_path
    end
  end
end

app/views/admin/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "エラー") %> ユーザの登録に失敗しました:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model:user, local: true, url:choose_new_or_edit ) do |f| %>

  <form>
    <div class="row">
      <div class="form-group col-md-6">
        <label>ユーザ名</label>
        <input type="text" class="form-control" name="user[name]" value="<%=@user.name%>">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>Eメール</label>
        <input type="text" class="form-control" name="user[email]" value="<%=@user.email%>">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>Admin権限</label>
         <%= f.select :admin,[["一般ユーザ", false], [ "管理者",true]], {}, {class: 'form-control'} %>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>パスワード</label>
        <input type="password" class="form-control" name="user[password]" id="exampleInputPassword1" placeholder="Password">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>パスワード確認</label>
        <input type="password" class="form-control" name="user[password_confirmation]" id="exampleInputPassword1" placeholder="Password">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-1">
        <button type="submit" class="btn btn-primary" name="commit">登録</button>
      </div>
    </div>
  </form>

<% end %>

app/views/admin/users/edit.html.erb
<div class="container">
  <h4>会員情報編集</h4>
  <%= render 'form', user: @user %>
</div>

app/views/admin/users/index.html.erb
<div class="container-fluid">

  <div class="row">
    <h4> ユーザ一覧 </h4>
  </div>

  <%= form_with url:'/admin/users', method: :get, local: true do |f| %>
  <%= f.hidden_field :search, value: 'true' %>
    <div class="row clearfix">
      <input type="text" class="form-control keyword-form clearfix" name="name" value="" placeholder="ユーザ名検索ワード">
      <button type="submit" class="btn btn-primary search-btn" name="commit">検索</button>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-4">
      <%= link_to "名前でソートする", admin_users_path(name_order: "true") %>
    </div>
  </div>

  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>ユーザ名</th>
        <th>Email</th>
        <th>タスク数</th>
        <th>ユーザ区分</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <%= render 'layouts/user', collection: @users %>
  </table>

  <%= paginate @users, left: 1, right: 3 %><br>

  <%= link_to 'ユーザの登録', new_admin_user_path %>

</div>

app/views/admin/users/new.html.erb
<div class="container">
  <h4>会員登録</h4>
  <%= render 'form', user: @user %>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <h4>ユーザ情報</h4>
  <form>

    <div class="row">
      <div class="form-group col-md-6">
        <label>ユーザ名</label>
        <input type="text" readonly class="form-control" name="user[name]" value="<%=@user.name%>">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>Eメール</label>
        <input type="text" readonly class="form-control" name="user[email]" value="<%=@user.email%>">
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-6">
        <label>ユーザ区分</label>
        <input type="select" readonly class="form-control show-form" value="<%= @user.admin ? '管理者' : '一般ユーザ'%>">
      </div>
    </div>

    <div class="row">
    <h4>ユーザ タスク一覧 </h4>
  </div>

  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>タスク名</th>
        <th>タスク詳細</th>
        <th>終了期限</th>
        <th>ステータス</th>
        <th>優先順位</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <%= render 'layouts/admin_task', collection: @tasks %>

    </table>

    <%= link_to '編集', edit_admin_user_path(@user) %> |
    <%= link_to '戻る', admin_users_path %>

  </form>
</div>