config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tasks#index'
  resources :tasks
  resources :users, only: %i[new create show edit update]
  resources :sessions, only: %i[new create destroy]

  namespace :admin do
    resources :users
    resources :tasks, only: [:index]
  end

  resources :labels
end

app/views/layouts/_admin_task.html.erb
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td class="task_row"><%= task.name %></td>
          <td><%= task.detail %></td>
          <td><%= task.deadline %></td>
          <td><%= task.status_i18n %></td>
          <td><%= task.priority_i18n %></td>
        </tr>
      <% end %>
    </tbody>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
      <ul id="menu-footer" class="common-footer__nav--list">
      <li id="menu-item-9" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-9">
      <p class="footer-item">会社</p>
      </li>
      <li id="menu-item-10" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-10">
      <p class="footer-item">プライバシーポリシー</p>
      </li>
      <li id="menu-item-11" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-11">
      <p class="footer-item">お問い合わせ</p>
      </li>

      </ul>
      <p class="copyright">Copyright © Junichi Sunaga All Rights Reserved.</p>
    </div>
</footer>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarExample1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/tasks">タスク管理App!</a>
        </div>

        <div class="navbar-collapse navbar-right collapse" id="navbarExample1">
          <ul class="nav navbar-nav float-right">
            <% if current_user %>
              <p class="navbar-text"><%= link_to "#{current_user.name}", user_path(current_user.id) %></p>
              <li ><p class="navbar-text"><%= link_to "タスク新規登録", new_task_path %></p></li>
              <li ><p class="navbar-text"><%= link_to "タスク一覧", tasks_path %></p></li>
              <li ><p class="navbar-text"><%= link_to "ラベル新規登録", new_label_path %></p></li>
              <li ><p class="navbar-text"><%= link_to "ラベル一覧", labels_path %></p></li>
              <% if current_user.admin %>
                <li ><p class="navbar-text"><%= link_to "ユーザ管理画面", admin_users_path %></p></li>
              <% end %>
              <li><p class="navbar-text"><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></p></li>
              <% else %>
              <li ><p class="navbar-text"><%= link_to "新規登録", new_user_path %></p></li>
              <li ><p class="navbar-text"><%= link_to "ログイン", new_session_path %></p></li>
              <% end %>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/_notice_message.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/layouts/_task.html.erb
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td class="task_row"><%= task.name %></td>
          <td><%= task.detail %></td>
          <td><%= task.deadline %></td>
          <td><%= task.status_i18n %></td>
          <td><%= task.priority_i18n %></td>
          <td>
          <% task.labels.each do |label| %>
            <span class="label label-default"><%= label.name %></span>
          <% end %>
          </td>
          <td><%= link_to '詳細', task %></td>
          <td><%= link_to '編集', edit_task_path(task) %></td>
          <td><%= link_to '削除', task, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } %></td>
        </tr>
      <% end %>
    </tbody>

app/views/layouts/_user.html.erb
    <tbody>
      <% @users.each_with_index do |user,idx| %>
        <tr>
          <td class="user_row"><%= user.name %></td>
          <td><%= user.email %></td>
          <td class="task_count_row"><%= user.tasks.count %></td>
          <td><%= user.admin ? '管理者' : '一般ユーザ'%></td>
          <td><%= link_to '詳細', admin_user_path(user) %></td>
          <td><%= link_to '編集', edit_admin_user_path(user) %></td>
          <td id=<%=idx%>><%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } %></td>
        </tr>
      <% end %>
    </tbody>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>

    <%= render 'layouts/header' %>

    <%= render 'layouts/notice_message' %>

    <div class="main">
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>

  </body>
</html>